name: Check Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  put-comment-test:
    uses: ./.github/workflows/lint.yml
    with:
      enable_pr_comment: true
    permissions:
      contents: read
      pull-requests: write