name: Test

on:
  push:
    paths:
      - "**.go"
      - "**.yaml"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Run Test
        run: go test ./... -cover -bench . -benchmem -func=cover.out
      - name: Report
        run: go tool cover -func=cover
