name: Test

on:
  push:
    paths:
      - "**.go"
      - "**.md"
      - "**.yaml"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Test
        run: go test -race -coverprofile="coverage.txt" -covermode=atomic ./... -bench . -benchmem

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
